/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.jbudget105325;

import javafx.application.Application;

public class App {


    public static void main(String[] args) {

        Application.launch(GUIView.class);

    }
}
